### ISSUE TITLE
further requirements?

### ISSUE THREAD

**Issue by barbalex** [nsingla/dbdiagrams#1]
I am a js dev and know nearly nothing of python.

So I am ideal to test if your readme is dummy-proof ;-)

I assume your instructions would only work on linux or macOS. Is that true? If so it should be stated in the readme. It seems quite obvious from the `sudo apt-get install libpq-dev python-dev` command but should be clarified.

So I ran `pip install -r requirements.txt` inside ubuntu on windows and got:

```
alex@pca:/mnt/c/Users/alexa/dbdiagrams$ pip install -r requirements.txt
Collecting numpy==1.17.0 (from -r requirements.txt (line 1))
  Could not find a version that satisfies the requirement numpy==1.17.0 (from -r requirements.txt (line 1)) (from versions: 1.3.0, 1.4.1, 1.5.0, 1.5.1, 1.6.0, 1.6.1, 1.6.2, 1.7.0, 1.7.1, 1.7.2, 1.8.0, 1.8.1, 1.8.2, 1.9.0, 1.9.1, 1.9.2, 1.9.3, 1.10.0, 1.10.0.post2, 1.10.1, 1.10.2, 1.10.3, 1.10.4, 1.11.0b3, 1.11.0rc1, 1.11.0rc2, 1.11.0, 1.11.1rc1, 1.11.1, 1.11.2rc1, 1.11.2, 1.11.3, 1.12.0b1, 1.12.0rc1, 1.12.0rc2, 1.12.0, 1.12.1rc1, 1.12.1, 1.13.0rc1, 1.13.0rc2, 1.13.0, 1.13.1, 1.13.3, 1.14.0rc1, 1.14.0, 1.14.1, 1.14.2, 1.14.3, 1.14.4, 1.14.5, 1.14.6, 1.15.0rc1, 1.15.0rc2, 1.15.0, 1.15.1, 1.15.2, 1.15.3, 1.15.4, 1.16.0rc1, 1.16.0rc2, 1.16.0, 1.16.1, 1.16.2, 1.16.3, 1.16.4)
No matching distribution found for numpy==1.17.0 (from -r requirements.txt (line 1))
You are using pip version 18.1, however version 19.2.3 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```

I then realized that python was installed in version 2.7 and tried to install v3. But having no idea what python really is about it seems that I butchered something because now I get:
```
(env) alex@pca:/mnt/c/Users/alexa/dbdiagrams$ pip install -r requirements.txt
bash: /mnt/c/Users/alexa/dbdiagrams/env/bin/pip: /mnt/c/Users/alexa/dbdiagrams/env/bin/python3: bad interpreter: No such file or directory
```

even though:
```
(env) alex@pca:/mnt/c/Users/alexa/dbdiagrams$ python3 --version
Python 3.5.2
```

So maybe it would help python noobs if there were some information on what has to happen _before_ the commands mentioned in the readme are run and how that can be tested.

**Comment by nsingla** [comment]
My apologies. Looks like now you've both versions of python now, if you've no use for python2.7 - I would suggest to point your /usr/bin/python to the newer version by running following commands:

'''
sudo rm /usr/bin/python
sudo ln -s /usr/bin/python3 /usr/bin/python
'''

the output of following command should be 3.5.2:
'''
python --version
'''

If you plan to utilize both versions of python(which some people have to do), ideally you can prefix python3 on every command, for ex.

'''
python3 -m pip install packagename
python3 hello.py
'''

If you go this route, only thing you might have to change is the the /usr/bin/python path to /usr/bin/python3 in the first line of generate_code script.

Hope this helps !

**Comment by barbalex** [comment]
Sorry to say still no cigar :-(

After doing:
```
sudo rm /usr/bin/python
sudo ln -s /usr/bin/python3 /usr/bin/python
```

`python --version` returns 3.5.2. So far so good.

`pip install -r requirements.txt` returns this though:
```
alex@pca:/mnt/c/Users/alexa/dbdiagrams$ pip install -r requirements.txt
Traceback (most recent call last):
  File "/usr/local/bin/pip", line 7, in <module>
    from pip._internal import main
ImportError: No module named 'pip._internal'
```

I also tried changing the first line in the generate_code script. Without any luck. I may well have changed it wrong - having no idea how python works.

I also tried installing on my MacBook Pro. There too, Python was installed in version 2.7.10. So I tried
`sudo rm /usr/bin/python` but got an error telling me `Operation not permitted`. So installing Python 3.7 hasn't helped there either.

**Comment by nsingla** [comment]
Sorry again !
If python --version is returning 3.5.2. It should technically now work with python3

But seems like pip has issue. pip is a package installer for python.
can you give me your full output of:
`pip --version`

If you're on python 3 already with python , no need to change the code in generate_code etc. I would try to help fix your pip issue.

**Comment by nsingla** [comment]
re: mac issue, I'm not a mac user but may be this can help :

https://stackoverflow.com/questions/32659348/operation-not-permitted-when-on-root-el-capitan-rootless-disabled

**Comment by barbalex** [comment]
On Ubuntu on Windows 10:
```
alex@pca:/mnt/c/Users/alexa/dbdiagrams$ pip --version
Traceback (most recent call last):
  File "/usr/local/bin/pip", line 7, in <module>
    from pip._internal import main
ImportError: No module named 'pip._internal'
```

On macOS I get: `-bash: pip: command not found`

Please do not excuse yourself. It makes me feel guilty as you have built this intriguing tool and decided to let us all profit from it. It is not your fault that python noobs like me are fighting with python. It is very generous of you to help. It's up to me to excuse myself for bugging you with stuff that is unrelated to what you built.

**Comment by nsingla** [comment]
I get to learn new things with such issues as well...so happy to help anytime.
I wish I could solve this one for you in one definite answer, but how about you try this one:

https://stackoverflow.com/questions/49940813/pip-no-module-named-internal

**Comment by barbalex** [comment]
`sudo apt-get install python3-pip` worked on Ubuntu on Windows 10, thanks for the link.

When running `pip install -r requirements.txt` I got:

```
alex@pca:/mnt/c/Users/alexa/dbdiagrams$ pip install -r requirements.txt
Requirement already satisfied: numpy==1.17.0 in /usr/local/lib/python3.5/dist-packages (from -r requirements.txt (line 1)) (1.17.0)
Collecting pandas==0.25.0 (from -r requirements.txt (line 2))
  ERROR: Could not find a version that satisfies the requirement pandas==0.25.0 (from -r requirements.txt (line 2)) (from versions: 0.1, 0.2b0, 0.2b1, 0.2, 0.3.0b0, 0.3.0b2, 0.3.0, 0.4.0, 0.4.1, 0.4.2, 0.4.3, 0.5.0, 0.6.0, 0.6.1, 0.7.0rc1, 0.7.0, 0.7.1, 0.7.2, 0.7.3, 0.8.0rc1, 0.8.0rc2, 0.8.0, 0.8.1, 0.9.0, 0.9.1, 0.10.0, 0.10.1, 0.11.0, 0.12.0, 0.13.0, 0.13.1, 0.14.0, 0.14.1, 0.15.0, 0.15.1, 0.15.2, 0.16.0, 0.16.1, 0.16.2, 0.17.0, 0.17.1, 0.18.0, 0.18.1, 0.19.0rc1, 0.19.0, 0.19.1, 0.19.2, 0.20.0rc1, 0.20.0, 0.20.1, 0.20.2, 0.20.3, 0.21.0rc1, 0.21.0, 0.21.1, 0.22.0, 0.23.0rc2, 0.23.0, 0.23.1, 0.23.2, 0.23.3, 0.23.4, 0.24.0rc1, 0.24.0, 0.24.1, 0.24.2)
ERROR: No matching distribution found for pandas==0.25.0 (from -r requirements.txt (line 2))
```
Weird, as https://pandas.pydata.org shows lists v0.25.1 as the up to date version. So I changed the pandas version to 0.24.2. I did run `sudo apt-get update` before but maybe that is not relevant for python dependencies?

Next `pip install -r requirements.txt` outputs this (brace yourself):
```
alex@pca:/mnt/c/Users/alexa/dbdiagrams$ pip install -r requirements.txt
Requirement already satisfied: numpy==1.17.0 in /usr/local/lib/python3.5/dist-packages (from -r requirements.txt (line 1)) (1.17.0)
Requirement already satisfied: pandas==0.24.2 in /usr/local/lib/python3.5/dist-packages (from -r requirements.txt (line 2)) (0.24.2)
Collecting psycopg2==2.8.3 (from -r requirements.txt (line 3))
  Using cached https://files.pythonhosted.org/packages/5c/1c/6997288da181277a0c29bc39a5f9143ff20b8c99f2a7d059cfb55163e165/psycopg2-2.8.3.tar.gz
Requirement already satisfied: python-dateutil==2.8.0 in /usr/local/lib/python3.5/dist-packages (from -r requirements.txt (line 4)) (2.8.0)
Requirement already satisfied: pytz==2019.2 in /usr/local/lib/python3.5/dist-packages (from -r requirements.txt (line 5)) (2019.2)
Requirement already satisfied: six==1.12.0 in /usr/local/lib/python3.5/dist-packages (from -r requirements.txt (line 6)) (1.12.0)
Building wheels for collected packages: psycopg2
  Building wheel for psycopg2 (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-leyt3e3e/psycopg2/setup.py'"'"'; __file__='"'"'/tmp/pip-install-leyt3e3e/psycopg2/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-zd577shk --python-tag cp35
       cwd: /tmp/pip-install-leyt3e3e/psycopg2/
  Complete output (42 lines):
  /usr/lib/python3.5/distutils/dist.py:261: UserWarning: Unknown distribution option: 'python_requires'
    warnings.warn(msg)
  /usr/lib/python3.5/distutils/dist.py:261: UserWarning: Unknown distribution option: 'project_urls'
    warnings.warn(msg)
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.5
  creating build/lib.linux-x86_64-3.5/psycopg2
  copying lib/__init__.py -> build/lib.linux-x86_64-3.5/psycopg2
  copying lib/_ipaddress.py -> build/lib.linux-x86_64-3.5/psycopg2
  copying lib/_json.py -> build/lib.linux-x86_64-3.5/psycopg2
  copying lib/_lru_cache.py -> build/lib.linux-x86_64-3.5/psycopg2
  copying lib/_range.py -> build/lib.linux-x86_64-3.5/psycopg2
  copying lib/compat.py -> build/lib.linux-x86_64-3.5/psycopg2
  copying lib/errorcodes.py -> build/lib.linux-x86_64-3.5/psycopg2
  copying lib/errors.py -> build/lib.linux-x86_64-3.5/psycopg2
  copying lib/extensions.py -> build/lib.linux-x86_64-3.5/psycopg2
  copying lib/extras.py -> build/lib.linux-x86_64-3.5/psycopg2
  copying lib/pool.py -> build/lib.linux-x86_64-3.5/psycopg2
  copying lib/sql.py -> build/lib.linux-x86_64-3.5/psycopg2
  copying lib/tz.py -> build/lib.linux-x86_64-3.5/psycopg2
  running build_ext
  building 'psycopg2._psycopg' extension
  creating build/temp.linux-x86_64-3.5
  creating build/temp.linux-x86_64-3.5/psycopg
  x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -DPSYCOPG_VERSION=2.8.3 (dt dec pq3 ext lo64) -DPG_VERSION_NUM=90519 -DHAVE_LO64=1 -I/usr/include/python3.5m -I. -I/usr/include/postgresql -I/usr/include/postgresql/9.5/server -c psycopg/psycopgmodule.c -o build/temp.linux-x86_64-3.5/psycopg/psycopgmodule.o -Wdeclaration-after-statement
  In file included from psycopg/psycopgmodule.c:27:0:
  ./psycopg/psycopg.h:34:20: fatal error: Python.h: No such file or directory
  compilation terminated.

  It appears you are missing some prerequisite to build the package from source.

  You may install a binary package by installing 'psycopg2-binary' from PyPI.
  If you want to install psycopg2 from source, please install the packages
  required for the build and try again.

  For further information please check the 'doc/src/install.rst' file (also at
  <http://initd.org/psycopg/docs/install.html>).

  error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for psycopg2
  Running setup.py clean for psycopg2
Failed to build psycopg2
Installing collected packages: psycopg2
  Running setup.py install for psycopg2 ... error
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-leyt3e3e/psycopg2/setup.py'"'"'; __file__='"'"'/tmp/pip-install-leyt3e3e/psycopg2/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-cnfu9wtb/install-record.txt --single-version-externally-managed --compile
         cwd: /tmp/pip-install-leyt3e3e/psycopg2/
    Complete output (42 lines):
    /usr/lib/python3.5/distutils/dist.py:261: UserWarning: Unknown distribution option: 'python_requires'
      warnings.warn(msg)
    /usr/lib/python3.5/distutils/dist.py:261: UserWarning: Unknown distribution option: 'project_urls'
      warnings.warn(msg)
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.5
    creating build/lib.linux-x86_64-3.5/psycopg2
    copying lib/__init__.py -> build/lib.linux-x86_64-3.5/psycopg2
    copying lib/_ipaddress.py -> build/lib.linux-x86_64-3.5/psycopg2
    copying lib/_json.py -> build/lib.linux-x86_64-3.5/psycopg2
    copying lib/_lru_cache.py -> build/lib.linux-x86_64-3.5/psycopg2
    copying lib/_range.py -> build/lib.linux-x86_64-3.5/psycopg2
    copying lib/compat.py -> build/lib.linux-x86_64-3.5/psycopg2
    copying lib/errorcodes.py -> build/lib.linux-x86_64-3.5/psycopg2
    copying lib/errors.py -> build/lib.linux-x86_64-3.5/psycopg2
    copying lib/extensions.py -> build/lib.linux-x86_64-3.5/psycopg2
    copying lib/extras.py -> build/lib.linux-x86_64-3.5/psycopg2
    copying lib/pool.py -> build/lib.linux-x86_64-3.5/psycopg2
    copying lib/sql.py -> build/lib.linux-x86_64-3.5/psycopg2
    copying lib/tz.py -> build/lib.linux-x86_64-3.5/psycopg2
    running build_ext
    building 'psycopg2._psycopg' extension
    creating build/temp.linux-x86_64-3.5
    creating build/temp.linux-x86_64-3.5/psycopg
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -DPSYCOPG_VERSION=2.8.3 (dt dec pq3 ext lo64) -DPG_VERSION_NUM=90519 -DHAVE_LO64=1 -I/usr/include/python3.5m -I. -I/usr/include/postgresql -I/usr/include/postgresql/9.5/server -c psycopg/psycopgmodule.c -o build/temp.linux-x86_64-3.5/psycopg/psycopgmodule.o -Wdeclaration-after-statement
    In file included from psycopg/psycopgmodule.c:27:0:
    ./psycopg/psycopg.h:34:20: fatal error: Python.h: No such file or directory
    compilation terminated.

    It appears you are missing some prerequisite to build the package from source.

    You may install a binary package by installing 'psycopg2-binary' from PyPI.
    If you want to install psycopg2 from source, please install the packages
    required for the build and try again.

    For further information please check the 'doc/src/install.rst' file (also at
    <http://initd.org/psycopg/docs/install.html>).

    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-leyt3e3e/psycopg2/setup.py'"'"'; __file__='"'"'/tmp/pip-install-leyt3e3e/psycopg2/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-cnfu9wtb/install-record.txt --single-version-externally-managed --compile Check the logs for full command output.
```

**Comment by nsingla** [comment]
In my step 4, I have mentioned to install a pre-requisite for  psycopg2. Were you able to install that ? only then run the requirements.txt install

`sudo apt-get install libpq-dev python-dev `

**Comment by barbalex** [comment]
Yep:
```
alex@pca:/mnt/c/Users/alexa/dbdiagrams$ sudo apt-get install libpq-dev python-dev
Reading package lists... Done
Building dependency tree
Reading state information... Done
libpq-dev is already the newest version (9.5.19-0ubuntu0.16.04.1).
python-dev is already the newest version (2.7.12-1~16.04).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
```

**Comment by barbalex** [comment]
Hm. Is that python v2.7.12 mentioned there?

**Comment by nsingla** [comment]
yea, that might be an issue, although I'm running same version but I've postgres also installed which is an alternate pre-requisite so may be. I will update my readme if this works for you :+1: 
(please replace x in 3.x with your corresponding version of python)

`sudo apt-get install python3.x-dev`


reference : https://stackoverflow.com/questions/26053982/setup-script-exited-with-error-command-x86-64-linux-gnu-gcc-failed-with-exit

**Comment by barbalex** [comment]
I did `sudo apt-get install python3-dev`.

With pandas v0.24.2 I then did `pip install -r requirements.txt`:
```
alex@pca:/mnt/c/Users/alexa/dbdiagrams$ pip install -r requirements.txt
Requirement already satisfied: numpy==1.17.0 in /usr/local/lib/python3.5/dist-packages (from -r requirements.txt (line 1)) (1.17.0)
Requirement already satisfied: pandas==0.24.2 in /usr/local/lib/python3.5/dist-packages (from -r requirements.txt (line 2)) (0.24.2)
Collecting psycopg2==2.8.3 (from -r requirements.txt (line 3))
  Using cached https://files.pythonhosted.org/packages/5c/1c/6997288da181277a0c29bc39a5f9143ff20b8c99f2a7d059cfb55163e165/psycopg2-2.8.3.tar.gz
Requirement already satisfied: python-dateutil==2.8.0 in /usr/local/lib/python3.5/dist-packages (from -r requirements.txt (line 4)) (2.8.0)
Requirement already satisfied: pytz==2019.2 in /usr/local/lib/python3.5/dist-packages (from -r requirements.txt (line 5)) (2019.2)
Requirement already satisfied: six==1.12.0 in /usr/local/lib/python3.5/dist-packages (from -r requirements.txt (line 6)) (1.12.0)
Building wheels for collected packages: psycopg2
  Building wheel for psycopg2 (setup.py) ... done
  Created wheel for psycopg2: filename=psycopg2-2.8.3-cp35-cp35m-linux_x86_64.whl size=361068 sha256=a9c5f5c039fca498e60896723e2087446c346057f55dd293571764cb36e1bf6b
  Stored in directory: /home/alex/.cache/pip/wheels/48/06/67/475967017d99b988421b87bf7ee5fad0dad789dc349561786b
Successfully built psycopg2
Installing collected packages: psycopg2
ERROR: Could not install packages due to an EnvironmentError: [Errno 13] Permission denied: '/usr/local/lib/python3.5/dist-packages/psycopg2'
Consider using the `--user` option or check the permissions.
```
Then `sudo pip install -r requirements.txt`:
```
alex@pca:/mnt/c/Users/alexa/dbdiagrams$ sudo pip install -r requirements.txt
WARNING: The directory '/home/alex/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
WARNING: The directory '/home/alex/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Requirement already satisfied: numpy==1.17.0 in /usr/local/lib/python3.5/dist-packages (from -r requirements.txt (line 1)) (1.17.0)
Requirement already satisfied: pandas==0.24.2 in /usr/local/lib/python3.5/dist-packages (from -r requirements.txt (line 2)) (0.24.2)
Collecting psycopg2==2.8.3 (from -r requirements.txt (line 3))
Requirement already satisfied: python-dateutil==2.8.0 in /usr/local/lib/python3.5/dist-packages (from -r requirements.txt (line 4)) (2.8.0)
Requirement already satisfied: pytz==2019.2 in /usr/local/lib/python3.5/dist-packages (from -r requirements.txt (line 5)) (2019.2)
Requirement already satisfied: six==1.12.0 in /usr/local/lib/python3.5/dist-packages (from -r requirements.txt (line 6)) (1.12.0)
Installing collected packages: psycopg2
Successfully installed psycopg2-2.8.3
```

Nice!

```
alex@pca:/mnt/c/Users/alexa/dbdiagrams$ ./generate_code
Success! generated code saved in output file
```

Only thing is: The output file does not seem to resemble my database:

```


Table "geography_columns" {
"f_table_catalog" name 
"f_table_schema" name 
"f_table_name" name 
"f_geography_column" name 
"coord_dimension" int4 
"srid" int4 
"type" text 
}

Table "geometry_columns" {
"f_table_catalog" varchar 
"f_table_schema" name 
"f_table_name" name 
"f_geometry_column" name 
"coord_dimension" int4 
"srid" int4 
"type" varchar 
}

Table "migrations" {
"id" int4 [pk]
"name" varchar 
"hash" varchar 
"executed_at" timestamp 
}

Table "raster_columns" {
"r_table_catalog" name 
"r_table_schema" name 
"r_table_name" name 
"r_raster_column" name 
"srid" int4 
"scale_x" float8 
"scale_y" float8 
"blocksize_x" int4 
"blocksize_y" int4 
"same_alignment" bool 
"regular_blocking" bool 
"num_bands" int4 
"pixel_types" _text 
"nodata_values" _float8 
"out_db" _bool 
"extent" geometry 
"spatial_index" bool 
}

Table "raster_overviews" {
"o_table_catalog" name 
"o_table_schema" name 
"o_table_name" name 
"o_raster_column" name 
"r_table_catalog" name 
"r_table_schema" name 
"r_table_name" name 
"r_raster_column" name 
"overview_factor" int4 
}

Table "spatial_ref_sys" {
"srid" int4 [pk]
"auth_name" varchar 
"auth_srid" int4 
"srtext" varchar 
"proj4text" varchar 
}

Ref: "spatial_ref_sys"."srid" < "geography_columns"."srid"
Ref: "spatial_ref_sys"."srid" < "geometry_columns"."srid"
Ref: "spatial_ref_sys"."srid" < "raster_columns"."srid"
```

**Comment by nsingla** [comment]
Nice !!

Strange that code doesn't resemble your database. dbname in settings.conf is correct?

Other way to check this is run this query(it is present in settings.conf, this is how my code pulls in the schema) in your database:

```
 SELECT c.table_name, c.column_name, c.udt_name datatype, 
		case when k.constraint_name is null then 0 else 1 end is_pk 
	FROM information_schema.columns c left join 
		information_schema.key_column_usage k
			on c.table_name = k.table_name
			and c.column_name = k.column_name
			and RIGHT(constraint_name, 4) = 'pkey'
	WHERE c.table_schema = 'public'
	order by c.table_name, c.ordinal_position
```

**Comment by barbalex** [comment]
Wow. Working nice now: I had not noticed that inside the sql I had to replace the table_schema.
Thanks A LOT.
